# ========================================
# SERVER PORT
# ========================================
server.port=${SERVER_PORT}

# ========================================
# DATABASE
# ========================================
tenant.driver-class-name=com.mysql.cj.jdbc.Driver
tenant.jdbc-url-template=jdbc:mysql://localhost:3306/{database}
tenant.username=root
tenant.password=12345

# ========================================
# HIRAKI
# ========================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# ========================================
# JPA
# ========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ========================================
# JWT
# ========================================

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

# ========================================
# ACTUATOR
# ========================================

management.endpoints.web.exposure.include=*
