spring:
  application:
    name: backend

  profiles:
    active: dev

  config:
    import: optional:file:.env[.properties]

server:
  servlet:
    context-path: /colegio/api/v1

springdoc:
  swagger-ui:
    path: /docs